INSERT INTO phrases (id, sense_id, phrase, definition) VALUES
('1', '1', 'to abandon oneself to something', 'To let oneself be completely controlled by something, often in a carefree or unrestrained manner.'),
('2', '2', 'ability to adapt', 'The power or capacity to change or modify in order to survive or fit new conditions.'),
('3', '2', 'within one''s ability', 'Within one''s powers, capabilities, or resources.'),
('4', '3', 'more than able', 'Having more ability or power than necessary.'),
('5', '3', 'beyond one''s abilities', 'Too difficult for someone to do because they lack the required ability or power.'),
('6', '4', 'Around about', 'Approximately; roughly'),
('7', '4', 'In about an hour', 'Approximately one hour from now'),
('8', '5', 'What''s about?', 'What is happening or being planned?'),
('9', '5', 'Around about', 'In or near the general area; approximately'),
('10', '6', 'a bird in the air above', 'an expression used to describe a situation or problem that has been resolved'),
('11', '6', 'keep an eye above', 'to keep a watchful lookout for potential problems or opportunities'),
('12', '7', 'above all else', 'more important than anything else'),
('13', '7', 'above the fold', 'a position on a newspaper or website that is easily visible when it is first opened, before any pages are scrolled'),
('14', '8', 'Abroad and at home', 'Someone who is widely accepted and respected in many different countries.'),
('15', '8', 'Set sail abroad', 'To leave one''s own country by ship for a foreign land.'),
('16', '9', 'an absolute beginner', 'someone who has no experience or knowledge about something'),
('17', '9', 'absolutely necessary', 'something that is essential, crucial, or indispensable'),
('18', '10', 'absolutely fine', 'Very well, completely alright'),
('19', '10', 'absolutely no chance', 'There is absolutely no possibility, there is not the slightest chance'),
('20', '11', 'an academic year', 'The period between the start and end of a school or university''s teaching sessions.'),
('21', '11', 'an academic qualification', 'A degree or other formal recognition of educational achievement.'),
('22', '13', 'in good faith, I accept', 'I am making this agreement honestly and with the intention of keeping my word'),
('23', '13', 'accept no substitutes', 'do not settle for anything less than the original or best'),
('24', '14', 'accept the challenge', 'to agree to do something difficult or risky that someone has proposed'),
('25', '14', 'accept in good faith', 'to believe and trust something is true without questioning it'),
('26', '15', 'have an access to something', 'Have the ability or permission to use or approach something.'),
('27', '15', 'grant someone access to something', 'Permit someone to approach, enter, or use something.'),
('28', '16', 'a narrow escape', 'an event in which one avoids a dangerous or potentially harmful situation by a small margin'),
('29', '16', 'to have an accident-prone personality', 'to frequently experience accidents due to carelessness or clumsiness');