  #version: '3.8'

  services: 
    backend:
      build: ./backend
      container_name: backend-slovko
      environment:
        - DATABASE_USER_NAME=${DB_USER}
        - DATABASE_PASSWORD=${DB_PASSWORD}
        - DATABASE_NAME=${DB_NAME}
        - DB_HOST=${DB_HOST}
        - JWT_SECRET=${JWT_SECRET}
        - JWT_LIFETIME=${JWT_LIFETIME}
      ports: 
        - "3000:3000"
      depends_on:
        - db
      volumes: 
        - ./backend:/app
        - /app/node_modules

    frontend: 
      build: ./frontend
      container_name: frontend-slovko
      env_file: .env
      ports: 
        - "8081:8081"
      volumes:
        - ./frontend:/app
    
    db:
      image: postgres:15
      container_name: postgres-slovko
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
      ports:
        - "5434:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

  volumes:
    postgres_data:
