INSERT INTO examples (id, sense_id, sentence, definition) VALUES
('1', '1', 'After realizing the futility of their cause, they chose to abandon it entirely.', 'They decided to give up on their project because it was not going well.'),
('2', '1', 'When the storm struck, the crew had no choice but to abandon ship.', 'The sailors were forced to leave the sinking boat.'),
('3', '2', 'He has the ability to play multiple musical instruments.', 'He has the power or capacity to play multiple musical instruments.'),
('4', '2', 'She lacked the ability to understand complex mathematical concepts.', 'She did not have the power or capacity to understand complex mathematical concepts.'),
('5', '3', 'He is able to speak several languages fluently.', 'He has the ability or power to speak several languages fluently.'),
('6', '3', 'She was unable to open the door due to the lock being jammed.', 'She did not have the ability or power to open the door because the lock was jammed.'),
('7', '4', 'She was talking about her recent vacation in Paris.', 'She was discussing details related to her recent trip to Paris.'),
('8', '4', 'I''m about to leave for work.', 'I am preparing to depart for work shortly.'),
('9', '4', 'Can you find out about the meeting schedule?', 'Could you discover the details regarding the meeting schedule?'),
('10', '5', 'I''ll be there about 5 o''clock.', 'I will arrive at approximately 5 o''clock'),
('11', '5', 'She lives around about here.', 'She resides in this general area'),
('12', '6', 'The clouds were above the mountain peak.', 'The clouds were higher than the top of the mountain.'),
('13', '6', 'Her grades were well above average.', 'Her grades were better than most students in her class.'),
('14', '7', 'Her test scores were above average.', 'She scored higher than the typical student.'),
('15', '7', 'I can''t reach the top shelf, it''s above my head.', 'The top shelf is too high for me to reach.'),
('16', '8', 'He is going abroad for a month-long vacation.', 'He is traveling to a foreign country for a one-month trip.'),
('17', '8', 'She decided to work abroad after graduation.', 'After completing her education, she chose to find employment in another country.'),
('18', '9', 'She has an absolute right to make her own decisions.', 'She is allowed to do whatever she wants without any restrictions.'),
('19', '9', 'The mathematical proof was considered as an absolute truth.', 'It was considered as completely accurate and undeniable.'),
('20', '10', 'I absolutely love this new movie.', 'I very completely and entirely love this new movie.'),
('21', '10', 'You must absolutely not tell anyone about our secret.', 'You should very completely and entirely not tell anyone about our secret.'),
('22', '11', 'She excelled academically in school and won numerous awards.', 'She was very intelligent and successful in her studies.'),
('23', '11', 'He published an academic paper on the topic of climate change.', 'He wrote a scientific research article about climate change.'),
('24', '12', 'She is an academic who specializes in medieval literature.', 'A person who holds a high degree from a university and conducts research, especially in a specific subject.'),
('25', '12', 'His academic interests lie in the field of astrophysics.', 'The areas or subjects that someone is particularly interested in learning about or studying.'),
('26', '12', 'The university offers a wide range of academic programs.', 'Courses of study that are taught at a college or university.'),
('27', '13', 'She accepted his invitation to dinner.', 'She agreed to go to dinner with him.'),
('28', '13', 'He has finally accepted that he cannot change the past.', 'He has acknowledged and come to terms with the fact that he cannot alter what has already happened.'),
('29', '14', 'The temperature is now within acceptable limits.', 'The temperature is now between a range that can be considered normal and comfortable.'),
('30', '14', 'I will only consider an offer if it meets my acceptable level of compensation.', 'I will only consider an offer if the proposed payment or benefits satisfy my minimum requirements.'),
('31', '15', 'She requested access to the restricted area.', 'She asked for permission to enter the limited-access zone.'),
('32', '15', 'The password gives you access to the computer system.', 'The password allows you to use the computer system.'),
('33', '15', 'He was denied access to the meeting room due to lack of invitation.', 'He was not allowed to enter the meeting room because he did not receive an invitation.'),
('34', '16', 'I was involved in a car accident on my way home last night.', 'The speaker had an unexpected event that caused damage to their vehicle while driving.'),
('35', '16', 'He tripped and accidentally broke the vase.', 'The man fell and unintentionally damaged a delicate object.');