INSERT INTO idioms (id, sense_id, idiom, definition) VALUES
('1', '1', 'abandon all hope', 'To give up entirely; to have no further chance of success.'),
('2', '2', 'able-bodied', 'Healthy and strong; physically fit.'),
('3', '2', 'not able to lift a finger', 'Unable to do any work or help at all.'),
('4', '3', 'can''t see the forest for the trees', 'Unable to see the big picture due to being focused on small details.'),
('5', '3', 'able-bodied seaman', 'A strong and healthy sailor.'),
('6', '4', 'It''s about time', 'It is long past the appropriate or expected time'),
('7', '4', 'On a shoestring (and about)', 'Living with minimal resources or budget'),
('8', '5', 'it''s about time', 'It is long past the appropriate or expected moment'),
('9', '5', 'on the one hand... on the other hand', 'Expressing two contrasting aspects or points of view'),
('10', '6', 'look down on someone', 'to regard someone with scorn or superiority'),
('11', '6', 'above board', 'honest, straightforward, and legal'),
('12', '7', 'look above one''s boots', 'to think too highly of oneself'),
('13', '7', 'above board', 'open and honest; not secret or dishonest'),
('14', '8', 'broad as the road', 'Very common or widespread; well known.'),
('15', '9', 'absolute rubbish', 'meaningless or worthless statements, ideas, or actions'),
('16', '9', 'in absolute awe', 'extremely impressed and filled with admiration'),
('17', '10', 'absolutely nowhere', 'In no place, not anywhere'),
('18', '10', 'absolutely nothing', 'Nothing at all'),
('19', '11', 'academic exercise', 'A pointless or theoretical activity that has no practical value.'),
('20', '11', 'academic freedom', 'The right of teachers, students, and scholars to express their opinions without fear of censorship or retribution.'),
('21', '13', 'accept with open arms', 'to welcome someone or something enthusiastically'),
('22', '13', 'it''s not up for debate/discussion; it''s accepted fact', 'something is widely known to be true and no further discussion is needed or appropriate'),
('23', '14', 'be beyond the pale', 'to be outside acceptable or proper limits'),
('24', '14', 'accept no substitutes', 'insist on having something specific, with no alternatives considered'),
('25', '15', 'have an open door policy', 'Have a welcoming and inviting attitude that encourages people to approach or enter.'),
('26', '15', 'keep someone at arm''s length', 'Maintain a distance, both physically and emotionally, from someone.'),
('27', '16', 'by accident', 'unintentionally, accidentally'),
('28', '16', 'accidents will happen', 'unfortunate events are unavoidable');